import { headers } from 'next/headers'
import "./globals.css";
import { Montserrat, Bebas_Neue } from 'next/font/google';
import { Footer, Header } from "./components";
import { getDefaultLanguage } from '@/app/utils/translations';

const montserrat = Montserrat({ subsets: ["latin"] });

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

const bebasNeue = Bebas_Neue({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-bebas-neue",
});

export const metadata = {
  title: "ДВЦНО",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const headersList = headers();
  const userLang = headersList.get('x-user-language') || getDefaultLanguage();

  return (
    <html lang={userLang}>
      <body className={`${montserrat.className} ${bebasNeue.variable} footer-sticky`}>
        <div className="container">
          <Header />
          <main>
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
