// import localFont from "next/font/local";
// import { Montserrat } from 'next/font/google';
// import "./globals.css";

// import { Footer, Header } from "../components";

// const montserrat = Montserrat({
//   weight: ['400', '500', '600', '700'],
//   style: ['normal'],
//   display: 'swap',
//   subsets: ['cyrillic', 'cyrillic-ext'],
// });

// const BebasNeue = localFont({
//   src: "../fonts/BebasNeue.ttf",
//   variable: '--second-family',
//   weight: "100 900",
// });

// export const metadata = {
//   title: "ДВЦНО",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
//   params,
// }) {
//   return (
//     <html lang={params.lang} >
//       <body className={`${montserrat.className} ${BebasNeue.variable} footer-sticky`}>
//         <div className="container">
//           <Header />
//         </div>
//         <main>
//           {children}
//         </main >
//         <Footer />
//       </body>
//     </html>
//   );
// }



// export async function generateStaticParams() {
//   return [{ lang: 'en-US' }, { lang: 'ru-Ru' }]
// }